/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerGoal {
  'targetRole' : string,
  'relevantSkills' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface InterviewFeedback {
  'communication' : bigint,
  'suggestions' : string,
  'overallScore' : bigint,
  'technicalKnowledge' : bigint,
}
export interface LearningPlan {
  'id' : bigint,
  'completedTasks' : Array<string>,
  'owner' : Principal,
  'plan' : Array<WeekPlan>,
}
export interface LearningProgress {
  'completedTasks' : bigint,
  'averageInterviewScore' : bigint,
  'averageQuizScore' : bigint,
  'quizzesTaken' : bigint,
  'interviewsCompleted' : bigint,
}
export interface Quiz {
  'id' : bigint,
  'attempts' : bigint,
  'score' : bigint,
  'questions' : Array<QuizQuestion>,
}
export interface QuizQuestion {
  'answerOptions' : Array<string>,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'category' : string,
}
export interface Resume {
  'id' : string,
  'name' : string,
  'bytes' : ExternalBlob,
  'uploadedBy' : Principal,
}
export interface Task {
  'name' : string,
  'description' : string,
  'resourceLink' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'targetRole' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeekPlan { 'tasks' : Array<Task>, 'weekNumber' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLearningPlan' : ActorMethod<[Array<WeekPlan>], undefined>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getCallerLearningPlan' : ActorMethod<[], [] | [LearningPlan]>,
  'getCallerResumes' : ActorMethod<[], Array<Resume>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerGoal' : ActorMethod<[Principal], [] | [CareerGoal]>,
  'getFirstIncompleteTask' : ActorMethod<[], Task>,
  'getInterviewFeedback' : ActorMethod<[Principal], [] | [InterviewFeedback]>,
  'getQuizResults' : ActorMethod<[Principal], [] | [Quiz]>,
  'getResumeByName' : ActorMethod<[string], Resume>,
  'getTasks' : ActorMethod<
    [],
    { 'incomplete' : Array<Task>, 'completed' : Array<string> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[Principal], [] | [LearningProgress]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isResumeImported' : ActorMethod<[string], boolean>,
  'markResumeAsImported' : ActorMethod<[string], undefined>,
  'markTaskComplete' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveInterviewFeedback' : ActorMethod<[InterviewFeedback], undefined>,
  'saveLearningProgress' : ActorMethod<[LearningProgress], undefined>,
  'saveQuizResults' : ActorMethod<[Quiz], undefined>,
  'setCareerGoal' : ActorMethod<[CareerGoal], undefined>,
  'updateTaskCompletionStatus' : ActorMethod<[Array<string>], undefined>,
  'uploadResume' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];