/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'resourceLink' : IDL.Opt(IDL.Text),
});
export const WeekPlan = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'weekNumber' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Resume = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'bytes' : ExternalBlob,
  'uploadedBy' : IDL.Principal,
});
export const LearningPlan = IDL.Record({
  'id' : IDL.Nat,
  'completedTasks' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'plan' : IDL.Vec(WeekPlan),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'targetRole' : IDL.Opt(IDL.Text),
});
export const CareerGoal = IDL.Record({
  'targetRole' : IDL.Text,
  'relevantSkills' : IDL.Vec(IDL.Text),
});
export const InterviewFeedback = IDL.Record({
  'communication' : IDL.Nat,
  'suggestions' : IDL.Text,
  'overallScore' : IDL.Nat,
  'technicalKnowledge' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'answerOptions' : IDL.Vec(IDL.Text),
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'category' : IDL.Text,
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'attempts' : IDL.Nat,
  'score' : IDL.Nat,
  'questions' : IDL.Vec(QuizQuestion),
});
export const LearningProgress = IDL.Record({
  'completedTasks' : IDL.Nat,
  'averageInterviewScore' : IDL.Nat,
  'averageQuizScore' : IDL.Nat,
  'quizzesTaken' : IDL.Nat,
  'interviewsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLearningPlan' : IDL.Func([IDL.Vec(WeekPlan)], [], []),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getCallerLearningPlan' : IDL.Func([], [IDL.Opt(LearningPlan)], ['query']),
  'getCallerResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerGoal' : IDL.Func([IDL.Principal], [IDL.Opt(CareerGoal)], ['query']),
  'getFirstIncompleteTask' : IDL.Func([], [Task], ['query']),
  'getInterviewFeedback' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(InterviewFeedback)],
      ['query'],
    ),
  'getQuizResults' : IDL.Func([IDL.Principal], [IDL.Opt(Quiz)], ['query']),
  'getResumeByName' : IDL.Func([IDL.Text], [Resume], ['query']),
  'getTasks' : IDL.Func(
      [],
      [
        IDL.Record({
          'incomplete' : IDL.Vec(Task),
          'completed' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(LearningProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isResumeImported' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markResumeAsImported' : IDL.Func([IDL.Text], [], []),
  'markTaskComplete' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveInterviewFeedback' : IDL.Func([InterviewFeedback], [], []),
  'saveLearningProgress' : IDL.Func([LearningProgress], [], []),
  'saveQuizResults' : IDL.Func([Quiz], [], []),
  'setCareerGoal' : IDL.Func([CareerGoal], [], []),
  'updateTaskCompletionStatus' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'uploadResume' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'resourceLink' : IDL.Opt(IDL.Text),
  });
  const WeekPlan = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'weekNumber' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Resume = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'bytes' : ExternalBlob,
    'uploadedBy' : IDL.Principal,
  });
  const LearningPlan = IDL.Record({
    'id' : IDL.Nat,
    'completedTasks' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'plan' : IDL.Vec(WeekPlan),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'targetRole' : IDL.Opt(IDL.Text),
  });
  const CareerGoal = IDL.Record({
    'targetRole' : IDL.Text,
    'relevantSkills' : IDL.Vec(IDL.Text),
  });
  const InterviewFeedback = IDL.Record({
    'communication' : IDL.Nat,
    'suggestions' : IDL.Text,
    'overallScore' : IDL.Nat,
    'technicalKnowledge' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'answerOptions' : IDL.Vec(IDL.Text),
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'attempts' : IDL.Nat,
    'score' : IDL.Nat,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const LearningProgress = IDL.Record({
    'completedTasks' : IDL.Nat,
    'averageInterviewScore' : IDL.Nat,
    'averageQuizScore' : IDL.Nat,
    'quizzesTaken' : IDL.Nat,
    'interviewsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLearningPlan' : IDL.Func([IDL.Vec(WeekPlan)], [], []),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getCallerLearningPlan' : IDL.Func([], [IDL.Opt(LearningPlan)], ['query']),
    'getCallerResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerGoal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CareerGoal)],
        ['query'],
      ),
    'getFirstIncompleteTask' : IDL.Func([], [Task], ['query']),
    'getInterviewFeedback' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(InterviewFeedback)],
        ['query'],
      ),
    'getQuizResults' : IDL.Func([IDL.Principal], [IDL.Opt(Quiz)], ['query']),
    'getResumeByName' : IDL.Func([IDL.Text], [Resume], ['query']),
    'getTasks' : IDL.Func(
        [],
        [
          IDL.Record({
            'incomplete' : IDL.Vec(Task),
            'completed' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(LearningProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isResumeImported' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markResumeAsImported' : IDL.Func([IDL.Text], [], []),
    'markTaskComplete' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveInterviewFeedback' : IDL.Func([InterviewFeedback], [], []),
    'saveLearningProgress' : IDL.Func([LearningProgress], [], []),
    'saveQuizResults' : IDL.Func([Quiz], [], []),
    'setCareerGoal' : IDL.Func([CareerGoal], [], []),
    'updateTaskCompletionStatus' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'uploadResume' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };